# Generated by Django 5.2.7 on 2025-10-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='dueno',
            new_name='dueño',
        ),
    ]
